apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-center.fullname" . }}
  labels:
    {{- include "config-center.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.config.datasource.password | quote }}
  SPRING_REDIS_PASSWORD: {{ .Values.config.redis.password | quote }}
  CC_ADMIN_PASSWORD: {{ .Values.config.security.adminPassword | quote }}
  CC_USER_PASSWORD: {{ .Values.config.security.userPassword | quote }}
  CC_MASTER_KEY: {{ .Values.config.encryption.masterKey | quote }}
